![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
print(my_array)
print(my_array[9::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [2]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [3]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [4]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)
print(matriz[::-1, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [5]:
print(matriz[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [6]:
print(matriz[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [7]:
print(matriz[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [8]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x[x == "Loro"])

['Loro' 'Loro']


In [9]:
print(x[np.where(x == "Loro")])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [10]:
arr = np.arange(1, 21).reshape(2, 5, 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [11]:
print(matriz[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [12]:
arr = np.zeros(10)
print(arr.nbytes)

arr[3] = 1
print(arr)

80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [13]:
vector = np.arange(10, 50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [14]:
v = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(v)[0])

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [15]:
matriz_random = np.random.random((10, 10))
print(matriz_random.min())
print(matriz_random.max())

0.014670017318277662
0.9837960861263393


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [16]:
vector = np.random.random(30)
print(vector.mean())

0.49895812346933704


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [17]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [18]:
tablero = np.zeros((8, 8), dtype=int)
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1
print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [19]:
patron = np.array([[0, 1], [1, 0]])
tablero = np.tile(patron, (4, 4))
print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [20]:
matriz = np.random.random((5, 5))
estandarizada = (matriz - np.mean(matriz)) / np.std(matriz)
print(estandarizada)

[[-0.84784813  1.3170607   1.23460998  1.6609338  -0.73592222]
 [-0.17912038 -0.21269304  1.31888116  0.09492234 -0.76191249]
 [-1.47614227 -1.1805068  -0.96738384 -1.17959544  0.93209625]
 [ 1.48858938  0.64587499 -0.1804754  -0.21804715 -1.07130368]
 [ 0.10751915  1.70234128  0.11270761 -1.29043192 -0.31415387]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [21]:
arr = np.arange(0, 11)
print(arr)

nuevo = np.where((arr > 3) & (arr < 8), -1, arr)
print(nuevo)

negado = np.where((arr > 3) & (arr < 8), arr, -arr)
print(negado)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[  0  -1  -2  -3   4   5   6   7  -8  -9 -10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [22]:
tablero = np.full((10, 10), " ")

tablero[0, 1] = "O"
tablero[1, 1] = "O"
tablero[1, 3] = "O"
tablero[1, 4] = "O"
tablero[1, 5] = "O"
tablero[1, 6] = "O"

tablero[0, 1] = "X"
tablero[0, 0] = "-"

tablero

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [23]:
import random

tablero2 = np.full((10, 10), " ")

eslora = 4
colocado = False

while not colocado:
    fila = random.randint(0, 9)
    col = random.randint(0, 9)
    orientacion = random.choice(["N", "S", "E", "O"])

    if orientacion == "E" and col + eslora <= 10:
        posiciones = [(fila, col + i) for i in range(eslora)]
    elif orientacion == "O" and col - eslora >= -1:
        posiciones = [(fila, col - i) for i in range(eslora)]
    elif orientacion == "S" and fila + eslora <= 10:
        posiciones = [(fila + i, col) for i in range(eslora)]
    elif orientacion == "N" and fila - eslora >= -1:
        posiciones = [(fila - i, col) for i in range(eslora)]
    else:
        continue

    if all(tablero2[f, c] == " " for f, c in posiciones):
        for f, c in posiciones:
            tablero2[f, c] = "O"
        colocado = True

tablero2

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', 'O', 'O', 'O', 'O', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')